import { PasswordService } from "./password.service.js";

describe("PasswordService", () => {
  let service: PasswordService;

  beforeEach(() => {
    service = new PasswordService();
  });

  it("hashes password and verifies successfully with bcrypt", async () => {
    const raw = "SuperSecretPassword#2026";
    const hash = await service.hash(raw);

    expect(hash).toBeDefined();
    expect(hash).not.toEqual(raw);
    expect(hash.startsWith("$2b$")).toBe(true);

    const isValid = await service.verify(raw, hash);
    expect(isValid).toBe(true);

    const isInvalid = await service.verify("WrongPassword", hash);
    expect(isInvalid).toBe(false);
  });

  it("verifies scrypt password hashes from seed.ts", async () => {
    // Known scrypt hash for 'CampusOS#2026' generated by seed format
    // scrypt$<N>$<r>$<p>$<salt-hex>$<derived-key-hex>
    const seedHash =
      "scrypt$16384$8$1$0123456789abcdef0123456789abcdef$5686034f71a084c79878dcbbce2cbf5aeeb312cb6f7b15eb89e6eb5f921586520fe813bf6b0aa90520a2f4da3bfab5d70b77b797e8499ea8d88e7b952f9c8cae";
    expect(await service.verify("wrong", seedHash)).toBe(false);

    // Test with freshly generated scrypt hash to test both matches and mismatches
    const { randomBytes, scryptSync } = await import("node:crypto");
    const salt = randomBytes(16);
    const derivedKey = scryptSync("DemoPassword#123", salt, 64, {
      N: 16384,
      r: 8,
      p: 1,
    });
    const customScryptHash = `scrypt$16384$8$1$${salt.toString("hex")}$${derivedKey.toString("hex")}`;

    const match = await service.verify("DemoPassword#123", customScryptHash);
    expect(match).toBe(true);

    const mismatch = await service.verify("WrongPassword", customScryptHash);
    expect(mismatch).toBe(false);
  });

  it("rejects invalid hash formats safely", async () => {
    expect(await service.verify("test", "")).toBe(false);
    expect(await service.verify("test", "plain-text-not-hash")).toBe(false);
    expect(await service.verify("test", "scrypt$invalid$parts")).toBe(false);
  });
});
